### ISSUE TITLE
Problem with cleanup service with image 1.0.35

### ISSUE THREAD

**Issue by jeffaco** [SUSE/azure-li-services#68]
Back from (yet another) vacation, testing image 1.0.35. Sorry for delay.

Upon booting the blade with image 1.0.35, no errors where shown on the console. Yet, when I took a look at the services, I observed this:

```
azurehost:~ # systemctl -a | grep azure-li
  azure-li-call.service                                                                                                loaded    inactive dead      Setup of Azure Li/VLi Script Caller
* azure-li-cleanup.service                                                                                             loaded    failed   failed    Cleanup/Uninstall Azure Li/VLi services
  azure-li-config-lookup.service                                                                                       loaded    inactive dead      Lookup and import Azure Li/VLi config file
  azure-li-install.service                                                                                             loaded    inactive dead      Installation of custom Azure Li/VLi addon packages
  azure-li-machine-constraints.service                                                                                 loaded    inactive dead      Validation of Azure Li/VLi machine constraints
  azure-li-network.service                                                                                             loaded    inactive dead      Setup of Azure Li/VLi network configuration
  azure-li-report.service                                                                                              loaded    inactive dead      Report status of Azure Li/VLi services
  azure-li-storage.service                                                                                             loaded    inactive dead      Setup of Azure Li/VLi Storage Mountpoints
  azure-li-system-setup.service                                                                                        loaded    inactive dead      System Setup of Azure Li/VLi machine
  azure-li-user.service                                                                                                loaded    inactive dead      Setup of Azure Li/VLi workload user
azurehost:~ # systemctl -l status azure-li-cleanup
* azure-li-cleanup.service - Cleanup/Uninstall Azure Li/VLi services
   Loaded: loaded (/usr/lib/systemd/system/azure-li-cleanup.service; bad; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2018-08-14 17:20:37 UTC; 6min ago
  Process: 53465 ExecStart=/usr/bin/azure-li-cleanup (code=exited, status=1/FAILURE)
 Main PID: 53465 (code=exited, status=1/FAILURE)

Aug 14 17:20:32 azurehost systemd[1]: Starting Cleanup/Uninstall Azure Li/VLi services...
Aug 14 17:20:37 azurehost azure-li-cleanup[53465]: Traceback (most recent call last):
Aug 14 17:20:37 azurehost azure-li-cleanup[53465]:   File "/usr/bin/azure-li-cleanup", line 11, in <module>
Aug 14 17:20:37 azurehost azure-li-cleanup[53465]:   File "/usr/lib/python3.4/site-packages/azure_li_services/units/cleanup.py", line 38, in main
Aug 14 17:20:37 azurehost azure-li-cleanup[53465]:   File "/usr/lib/python3.4/site-packages/azure_li_services/defaults.py", line 46, in get_service_reports
Aug 14 17:20:37 azurehost azure-li-cleanup[53465]: ImportError: No module named 'azure_li_services.status_report'
Aug 14 17:20:37 azurehost systemd[1]: azure-li-cleanup.service: Main process exited, code=exited, status=1/FAILURE
Aug 14 17:20:37 azurehost systemd[1]: Failed to start Cleanup/Uninstall Azure Li/VLi services.
Aug 14 17:20:37 azurehost systemd[1]: azure-li-cleanup.service: Unit entered failed state.
Aug 14 17:20:37 azurehost systemd[1]: azure-li-cleanup.service: Failed with result 'exit-code'.
Warning: azure-li-cleanup.service changed on disk. Run 'systemctl daemon-reload' to reload units.
azurehost:~ #
```

It looks like the cleanup service had some sort of a problem referencing a module. Thoughts?

**Comment by schaefi** [comment]
Uhm a bad bug, loading a module after deleting the package which provides it is not smart ;)
I'll fix it
