### ISSUE TITLE
Service azure-li-user fails in 1.0.38-Build2.2

### ISSUE THREAD

**Issue by jeffaco** [SUSE/azure-li-services#76]
It seems like service `azure-li-user` is a bear to work out, it's been problematic in the past three builds.

In the latest build, the service still fails with the following error:

```
azurehost:~ # systemctl status -l azure-li-user
* azure-li-user.service - Setup of Azure Li/VLi workload user
   Loaded: loaded (/usr/lib/systemd/system/azure-li-user.service; bad; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2018-08-22 18:02:10 UTC; 1min 56s ago
 Main PID: 37598 (code=exited, status=1/FAILURE)

Aug 22 18:02:10 linux azure-li-user[37598]: Traceback (most recent call last):
Aug 22 18:02:10 linux azure-li-user[37598]:   File "/usr/bin/azure-li-user", line 11, in <module>
Aug 22 18:02:10 linux azure-li-user[37598]:     load_entry_point('azure-li-services==1.1.7', 'console_scripts', 'azure-li-user')()
Aug 22 18:02:10 linux azure-li-user[37598]:   File "/usr/lib/python3.4/site-packages/azure_li_services/units/user.py", line 74, in main
Aug 22 18:02:10 linux azure-li-user[37598]:     raise AzureHostedException(user_setup_errors)
Aug 22 18:02:10 linux azure-li-user[37598]: azure_li_services.exceptions.AzureHostedException: [AzureHostedCommandException('umount: stderr: umount: /mnt: target is busy\n        (In some cases useful info about processes that\n         use the device is found by lsof(8) or fuser(1).)\n, stdout: (no output on stdout)',)]
Aug 22 18:02:10 linux systemd[1]: azure-li-user.service: Main process exited, code=exited, status=1/FAILURE
Aug 22 18:02:10 linux systemd[1]: Failed to start Setup of Azure Li/VLi workload user.
Aug 22 18:02:10 linux systemd[1]: azure-li-user.service: Unit entered failed state.
Aug 22 18:02:10 linux systemd[1]: azure-li-user.service: Failed with result 'exit-code'.
Warning: azure-li-user.service changed on disk. Run 'systemctl daemon-reload' to reload units.
azurehost:~ #
```

Seems like it's trying to unmount the YAML LUN. That's going to be problematic; I guess to unmount you'd need to make sure all other services are done, and that there's no timing/race conditions. Perhaps it's safest to handle this in the cleanup service, which runs after everything else is completed?

I'm still trying to get a viable build for PM testing. Once this is fixed, please generate a new `.xz` file for me to retest. Thanks.

**Comment by schaefi** [comment]
It's not problematic, it's just me overlooking that umount needs the same check that I have added for mount. My runtime testing doesn't face the parallel mount condition as you see it. I'll fix it and you can be sure that completes the mount/umount issue. A new image will go out to you today
